# run: conda env create -n <name> --file environment.yml

# conda env create -n gemini-flash-ocr --file Environment.yml
# conda activate gemini-flash-ocr
# cleanup:
#     conda env remove -n gemini-flash-ocr
name: gemini-flash-ocr
channels:
  - conda-forge
dependencies:
  - python=3.11
  - google-genai
