# run: conda env create -n <name> --file environment.yml
# conda env create -n gemini-ocr --file Environment.yml
# conda activate gemini-ocr
name: gemini-ocr
channels:
  - conda-forge
dependencies:
  - python=3.10
  - google-generativeai
